# Generated by Django 4.2.20 on 2025-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
